# Site settings
baseurl = "https://clarkeh627.github.io/mysite/"
languageCode = "en-us"
title = "Clarke Hardy"
theme = "hugo-highlights-theme"
publishDir = "docs"

# Enter your tracking code to enable Google analytics
googleAnalytics = "UA-163970776-1"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Clarke Hardy"
  description = "Clarke Hardy Stanford Physics Dark Matter"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "contact@clarkehardy.com"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.jpg and overlay.png to set the background.
  backgroundpersection = false
  avatar = "profile.jpg"

  # hero Section
  [params.hero]
    type = "hero"
    title = "Clarke Hardy"
    description = "Welcome"
    buttontext = "Start Here"

  # about section
  [[params.block]]
    id = "about"
    type = "text"
    title = "About me"
    avatar = "profile.jpg"
    description = "I'm a Ph.D. student in physics at Stanford University. I'm interested in learning about dark matter, one of the most intriguing and elusive mysteries of our universe today. I have worked on three different experiments that attempt to detect in here on Earth -- the [NEWS-G experiment](https://news-g.org/), which uses spherical proportional counters, the [PICO experiment](http://www.picoexperiment.com/), using bubble chambers, and now the [LZ experiment](https://lz.lbl.gov), a liquid xenon time projection chamber. You can learn more about my work by following the links below."
    buttontext = "next"
    # the picture is stored at static/images/

  # skill section
  [[params.block]]
    id = "skills"
    type = "list"
    title = "Find my work"
    description = "Below, you can find links to a few places that showcase the progress I and my colleagues have made on our search to understand dark matter."
    buttontext = "next"
    # the picture is stored at static/images/

    [[params.block.item]]
      icontype = "fab"
      icon = "fa-orcid"
      title = "Find my papers"
      url = "https://orcid.org/0000-0002-4989-1700"
      newtab = true

    [[params.block.item]]
      icontype = "fas"
      icon = "fa-book"
      title = "Read my thesis"
      url = "https://qspace.library.queensu.ca/handle/1974/26547"
      newtab = true

    [[params.block.item]]
      icontype = "fas"
      icon = "fa-file-pdf"
      title = "Download my CV"
      url = "content/CV.pdf"
      newtab = true

    [[params.block.item]]
      icontype = "fas"
      icon = "fa-envelope"
      title = "Email me"
      url = "#contact"
      newtab = false

    [[params.block.item]]
      icontype = "fab"
      icon = "fa-twitter"
      title = "Follow me"
      url = "https://twitter.com/clarkeahardy"
      newtab = true

    [[params.block.item]]
      icontype = "fab"
      icon = "fa-instagram"
      title = "Follow me"
      url = "https://instagram.com/clarkehardy"
      newtab = true

  # infos section
#  [[params.block]]
#    id = "infos"
#    type = "text"
#    title = "One more thing"
#    description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
#    # the picture is stored at static/images/

#  # custom section
#  [[params.block]]
#    id = "important"
#    # to make custom section copy <theme>/layouts/partials/text.html to /layouts/partials/custom.html and edit it according to your needs.
#    type = "custom"
#    title = "Don't forget"
#    description = "Curabitur massa ante, semper at massa et, semper pellentesque velit. Duis tempor est nisi, a gravida risus malesuada eget. Nunc rutrum arcu laoreet mauris sodales vehicula. Nunc iaculis felis ac dui egestas, vel ullamcorper tellus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia sem porttitor, fringilla metus at, convallis quam. Integer convallis a justo non pellentesque."
#    # the picture is stored at static/images/

  # contact form
  [[params.block]]
    id = "contact"
    type = "contact"
    title = "Email me"
    picture = "pic05.jpg"

    [params.block.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

#      [[params.footer.social]]
#        title = "Twitter"
#        icon = "fa-twitter"
#        link = "#"

#      [[params.footer.social]]
#        title = "Facebook"
#        icon = "fa-facebook"
#        link = "#"

#      [[params.footer.social]]
#        title = "Instagramm"
#        icon = "fa-instagram"
#        link = "#"

#      [[params.footer.social]]
#        title = "Dribbble"
#        icon = "fa-dribbble"
#        link = "#"

#      [[params.footer.social]]
#        title = "Email"
#        icon = "fa-envelope"
#        link = "#"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© Clarke Hardy 2020"
